### ISSUE TITLE
Format Preference

### ISSUE THREAD

**Issue by hansen7** [hansen7/TA-CAM#2]
## Zoom or Physical Meeting.

- hw501: physical

- kb670: either

- tpd29:  physical

- ng432: either

- pn309: either

- aw765:  either

- ky295:  either (virtual for 1st session)

- pr450: either

- jss88: either

- yy452: zoom

**Comment by ky295** [comment]
> ## Zoom or Physical Meeting.
> * ky295: happy with either. Am self-isolating at the moment so the first supervision would have to be virtual for me, unfortunately

**Comment by helenayyan** [comment]
yy452: I am working remotely at home, so i can also attend a zoom meeting. Sorry about this!

**Comment by tpd29** [comment]
physical

**Comment by tpd29** [comment]
tpd29: physical

**Comment by aw765** [comment]
aw765: happy with either

**Comment by DustinBaek** [comment]
happy with either

**Comment by patnev** [comment]
pn309: happy with either

**Comment by JuvrajSingh** [comment]
jss88: Happy with either

**Comment by ng432** [comment]
ng432: happy with either

**Comment by puria-radmard** [comment]
pr450: either is good
